name: Build and Deploy Image

on:
  push:
    branches:
      - main
    paths:
      - "vllm_starter/**"
<<<<<<< HEAD
      - "requirements.txt"
=======
      - "pyproject.docker.toml"
>>>>>>> 08a6144 (fix: optimize dockerfile build)
      - "Dockerfile"
      - ".github/workflows/deploy.yml"
      - ".dockerignore"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v2

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yugasun/vllm-starter:latest
          registry: ${{ secrets.DOCKER_REGISTRY }}
          platforms: linux/amd64,linux/arm64
